postgresql:
  enabled: true
  postgresUsername: postgres
  postgresqlPassword: postgres
  postgresqlPostgresPassword: postgres
redis:
  enabled: true
  usePassword: false
result:
  image:
    tag: SA-243-storm-or-mojo-d94a1ae
vote:
  image:
    tag: SA-243-storm-or-mojo-d94a1ae
worker:
  image:
    tag: updating-cb26ce0
