postgresql:
  enabled: true
  postgresUsername: postgres
  postgresqlPassword: postgres
  postgresqlPostgresPassword: postgres
redis:
  enabled: true
  usePassword: false
result:
  image:
    tag: SA-245-cyclops-or-mojo-4eaf443
vote:
  image:
    tag: SA-245-cyclops-or-mojo-4eaf443
worker:
  image:
    tag: updating-cb26ce0
