apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-voting-app-istio-vote
  namespace: argocd
spec:
  project: argo-voting-app-istio
  source:
    repoURL: https://github.com/salesdemocf/argo-voting-app-istio.git
    path: argo-voting-app
    targetRevision: add-argo-rollout
  destination:
    server: https://kubernetes.default.svc
    namespace: development