apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name:  {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name  | quote }}
    heritage: {{ .Release.Service  | quote }}
    version: {{ .Values.image.tag | quote }}
spec:
  strategy:
    canary:
      canaryService: canary-vote-svc  # required
      stableService: stable-vote-svc  # required
      trafficRouting:
        istio:
          virtualService: 
            name: stable-vote-vsvc
            routes:
            - primary
      steps:
      - setWeight: 25
      - pause: {}