# Default values for worker.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
image: 
  repository: quay.io/salesdemocf/worker
  tag: latest

postgresql:
  postgresUsername: postgres
  postgresqlPassword: postgres

redis:
  usePassword: false

replicaCount: 1
